use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
target 'ProThirdpart_Example' do
  pod 'ProThirdpart', :path => '../'

  target 'ProThirdpart_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'

    pod 'SnapKit'  , '~> 4.2.0'
    pod 'SDWebImage'  , '~>  5.5.2'
    pod 'MBProgressHUD'
  end
end
